### ISSUE TITLE
Update Google Analytics embed code

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/ccnmtldjango#244]
Google Analytics has a new embed API that we should update our base template to:
https://developers.google.com/analytics/devguides/reporting/embed/v1/getting-started

**Comment by zmustapha** [comment]
I'll modify the base template

**Comment by zmustapha** [comment]
Actually, I am not sure. Analytics tacking code that Google gives in CCNMTL Analytics account is the following:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=GACODE"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'GACODE');
</script>
```
The link you gave points to a different use, the embed API, not the tracking code.

**Comment by nikolas** [comment]
Ah yeah.. the code you pasted is correct. https://support.google.com/analytics/answer/1008080?hl=en  I think that's the tracking code that we want to use.

**Comment by nikolas** [comment]
And some more detailed info here: https://developers.google.com/analytics/devguides/collection/gtagjs/ But basically, whatever it says in the CCNMTL Analytics account should be correct.
